sudo: required
services: 
  -docker
  
before_install:
  - docker build -t dmr1725/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dmr1725/docker-react npm run test

language: generic 